services:
    frontend:
      build: ./frontend
      ports:
        - "5000:5000"
      env_file:
        - ./frontend/.env
      volumes:
        - ./frontend:/app
      stdin_open: true
      tty: true
    
